package com.example.pojo;

import java.util.Date;

public class Liuyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.id
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.user_name
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.liuyan
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    private String liuyan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.time
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    private Date time;
    private String timeString;//非数据库字段，格式化时间
    

    public String getTimeString() {
		return timeString;
	}

	public void setTimeString(String timeString) {
		this.timeString = timeString;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.id
     *
     * @return the value of liuyan.id
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.id
     *
     * @param id the value for liuyan.id
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.user_name
     *
     * @return the value of liuyan.user_name
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.user_name
     *
     * @param userName the value for liuyan.user_name
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.liuyan
     *
     * @return the value of liuyan.liuyan
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public String getLiuyan() {
        return liuyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.liuyan
     *
     * @param liuyan the value for liuyan.liuyan
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public void setLiuyan(String liuyan) {
        this.liuyan = liuyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.time
     *
     * @return the value of liuyan.time
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.time
     *
     * @param time the value for liuyan.time
     *
     * @mbggenerated Sat Feb 24 14:46:04 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}